### ISSUE TITLE
Reference single source of truth for 'Implicit ARIA Semantics' topic

### ISSUE THREAD

**Issue by jameshopkins** [webspecs/html-aria#11]
There appears to be many different specifications (http://www.w3.org/TR/html5/dom.html#sec-strong-native-semantics, http://www.w3.org/TR/2015/WD-html-aria-20150414/#docconformance, http://rawgit.com/w3c/aria-in-html/master/index.html#first-rule-of-aria-use) across the W3C estate that describe the subject of implicit ARIA semantics

The information can range from in-depth tables describing semantic validity in varying contexts, to allusion of the aforementioned subject.

@stevefaulkner I notice you're the only co-author on all three specs I've mentioned. Is there some way we can provide a single source of truth for this subject?

I'll refrain from disseminating this issue to https://www.w3.org/Bugs/Public/enter_bug.cgi?product=HTML%20WG or public-html@w3.org - who both have this topic included in varying forms.

CC @sideshowbarker

**Comment by stevefaulkner** [comment]
@jameshopkins 

The 'single source of [normative] truth' of how implict ARIA HTML semantics are expressed in browser implementations is HTML Accessibility API Mappings 1.0 http://www.w3.org/TR/html-aam-1.0/

For how the these are expressed as [normative] conformance requirements for web developers when using in HTML (5.1) (and what conformance checker implementations should report)
http://www.w3.org/TR/html-aria/

Using WAI-ARIA in HTML is an informative document 
http://w3c.github.io/aria-in-html/
"This document is informative only. Resources are for information purposes only, no endorsement implied."

If you look at the latest docs you should see that html 5.1 http://www.w3.org/TR/html51/ normatively references http://www.w3.org/TR/html-aam-1.0/ and http://www.w3.org/TR/html-aria/ or the editors drafts of them.
