### ISSUE TITLE
"No corresponding role" instead of "NONE"

### ISSUE THREAD

**Issue by jasonkiss** [webspecs/html-aria#12]
After some discussion (https://lists.w3.org/Archives/Member/member-pf-editors/2015JanMar/0030.html  - member-only), we decided to go with "No corresponding role" in the HTML-AAM for those HTML elements with no default ARIA role. We did this to avoid any potential confusion with role=none. 

Suggest the same approach for the Rules of ARIA attributes usage by HTML language feature  table.

**Comment by stevefaulkner** [comment]
fixed
