### ISSUE TITLE
FORM element should have no deafult role

### ISSUE THREAD

**Issue by jongund** [webspecs/html-aria#14]
I think making the FORM element have the default role be FORM landmark will lead to a lot random FORM landmarks.  I think there is alot of random use of the FORM element and most developers will not being thinking that they want this to be a landmark.

**Comment by stevefaulkner** [comment]
i agree, but the default role is not defined in this spec it is defined in http://w3c.github.io/aria/html-aam/html-aam.html please file a bug there https://www.w3.org/Bugs/Public/enter_bug.cgi?product=ARIA&component=HTML%20AAM

**Comment by jongund** [comment]
Done.

https://www.w3.org/Bugs/Public/show_bug.cgi?id=28799
