### ISSUE TITLE
img alt="" and role="presentation"

### ISSUE THREAD

**Issue by goetsu** [webspecs/html-aria#15]
I think that in the case of img with alt="" role="presentation must be allowed or defined as default implicit ARIA semantic

**Comment by goetsu** [comment]
@stevefaulkner say " On default role, see https://www.w3.org/Bugs/Public/show_bug.cgi?id=26149 "
here https://github.com/webspecs/html-aria/issues/16#issuecomment-99500861 
Ok with that but in that case role="presentation" must be allowed

**Comment by stevefaulkner** [comment]
ok I see, it says img with alt="" =  "No role or aria* attributes" 
I can add role=presentation, sure, but it seems redundant, what does it add?

**Comment by goetsu** [comment]
for example if some browser map a role="img" instead of none it will not be a conformance failure to use role="presentation" to fix that

**Comment by stevefaulkner** [comment]
role=presentation now allowed on img with alt=""
