### ISSUE TITLE
img without alt case

### ISSUE THREAD

**Issue by goetsu** [webspecs/html-aria#16]
I know that regarding HTML5  specs img must have an alt attribut except in some specific conditions : http://www.w3.org/TR/html5/embedded-content-0.html#guidance-for-conformance-checkers

I know that not having an alt attribut on img isn't a failure anymore if the img have a role="presentation" 

That's why I think that we must add a line in the table 
http://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html
to cover this case.

My suggestion is : 

img
role="img"
Any role
global aria-* attributes and any aria-* attributes applicable to the allowed roles

**Comment by stevefaulkner** [comment]
One issue is that we cannot have conformance in HTML5 be reliant upon the presence of an attribute defined in another spec. I have been told on numerous occasions its a layering violation. On default role, see https://www.w3.org/Bugs/Public/show_bug.cgi?id=26149

**Comment by goetsu** [comment]
For now the spec do not say anything on the case of img without alt that's not a good thing we must at least include it in the spec and then choose to say if you can use role/aria-* on it or not

but for example for me : 
http://www.oaa-accessibility.org/examplep/checkbox1/
must be conforming against ARIA in HTML spec

It's not conforming again HTML5 spec only but that's a different issue

**Comment by stevefaulkner** [comment]
ARIA in HTML is a module of the HTML spec, so is governed by its conformance criteria, so as i said previously img cannot be made conforming without alt by saying it is when role=presentation is present.

**Comment by goetsu** [comment]
I suppose I'm not clear.

I don't want to made conforming the img without alt when I use aria on it.

What I don't want is to have two errors when I use aria on img without alt, one for the img without alt and one for using aria on it.

As it's not defined for now I suppose conformance checker don't have that kind of issue but for developpers reading the spec it may look like you can't use aria on an img without alt so I think it's more clear to specify that you can. (knowing that even with aria on it's still on html5 error for img element)

**Comment by goetsu** [comment]
any final thought on my last comment ?

**Comment by stevefaulkner** [comment]
I have modified the img rules:
img alt="" allowed roles =presentation
img (no longer mentions alt) role:any

**Comment by stevefaulkner** [comment]
@goetsu 
note http://validator.w3.org/nu/ only throws one error for 
`<img src="p.gif" alt="" role="presentation">` or `<img src="p.gif" role="presentation">`
