### ISSUE TITLE
input type=checkbox should allow role=button and role=switch

### ISSUE THREAD

**Issue by jnurthen** [webspecs/html-aria#18]
It is very common to base toggle buttons (role=button with aria-pressed set to true/false) and role=switch on an HTML checkbox. This spec forbids this common practice and it should not.

**Comment by stevefaulkner** [comment]
@jnurthen do you have examples you can point me to of the use of checkbox as described?

**Comment by jnurthen** [comment]
As usual not in public space no. Sorry.

**Comment by stevefaulkner** [comment]
moved to https://github.com/w3c/html-aria/issues/
